on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.result }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Contains Add Readme in message subject
          ref: '84841e1cb19c7cf14edeb0b0041cead83ed2d8c7'
          fetch-depth: 0
      - uses: mstachniuk/ci-skip@tag-for-test
      - run: echo "::set-output name=result::${CI_SKIP}"
        id: result_step

  # this job should NOT be skipped
  test_job:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.ci-skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Output ci-skip: ${{ needs.check_skip.outputs.ci-skip }}"
          echo "Output ci-skip-not: ${{ needs.check_skip.outputs.ci-skip-not }}"
          echo "The main_job should NOT be skipped"
          exit 0
